### ISSUE TITLE
how to tie subscription with Application Lifecycle

### ISSUE THREAD

**Issue by rinav** [jacek-marchwicki/JavaWebsocketClient#16]
Thanks for this awesome Rx support. I need help in understanding how do I implement WebSockets so that it only lives for the Application Lifecycle.

I create a subscription in `onCreate()` of Application and unsubscribe in `onDestroy()`
Should I manage this subscription from an IntentService or if you have any other suggestions please let me know.

I also thought about implementing Sockets through GCMNetworkManager and manage subscription in this GCM task, but not sure if it's feasible or fit's my use case.

Please can you guide me in a correct direction

**Comment by jacek-marchwicki** [comment]
It depends from you needs.. but keeping socket connection through all application lifecycle is not good idea.. 

In our implementation we use:
`.compose(MoreOperators.cacheWithTimeout())` from [MoreOperators](https://github.com/jacek-marchwicki/rx-java-extensions/blob/master/rx-extensions/src/main/java/com/appunite/rx/operators/MoreOperators.java)

and subscribe in Activity.onStart and unsubscribe `Activity.onStop` but thanks `cacheWithTimeout()` its keept for 5 seconds after onStop
